# Generated by Django 2.1.12 on 2020-06-17 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200617_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='karma',
            field=models.CharField(default=' ', max_length=40),
        ),
    ]
